# SUPERSTORE DATA SET

In [ ]:
# IMPORTING LIBRARIES 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as datetime

# 1.Import dataset

In [ ]:
df = pd.read_csv("superstore_data.csv")
df

,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Customer Segment,Product ID,Product Name,Category,Region,...,Sales Amount,Cost Price,Profit,Payment Mode,Delivery Status,Supplier Name,Supplier Email,Stock Left,Auto Reorder,Reorder Quantity
0,ORD1000,2025-12-25,2025-12-27,CUST595,Sherry Thompson,Consumer,PROD6890,Dining Table,Furniture,North,...,4382.35,3653.39,728.96,UPI,Pending,Young Group,gford@peck-tucker.com,29,No,0
1,ORD1001,2024-04-08,2024-04-09,CUST183,Eric Olsen,Home Office,PROD3289,Snacks,Grocery,North,...,4858.30,4042.40,815.90,Cash,Cancelled,Fox-Williams,pattersonkimberly@clark.info,40,No,0
2,ORD1002,2025-01-29,2025-02-03,CUST590,John Armstrong,Consumer,PROD8638,Cooking Oil,Grocery,South,...,1579.20,959.15,620.05,Cash,Returned,Mann and Sons,brandonlutz@lopez.com,44,No,0
3,ORD1003,2025-05-29,2025-06-05,CUST582,Raymond Parker,Home Office,PROD5549,Mouse,Electronics,West,...,29421.00,19574.90,9846.10,Credit Card,Delivered,"Massey, Malone and Miller",norozco@miller.com,7,Yes,21
4,ORD1004,2025-03-02,2025-03-07,CUST530,Veronica Cole,Consumer,PROD4604,Cooking Oil,Grocery,South,...,32128.00,24292.49,7835.51,Cash,Delivered,Munoz-Robinson,dawn94@smith.com,27,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD1995,2024-09-10,2024-09-12,CUST985,Christopher Jordan,Corporate,PROD6665,Pen,Office supplies,North,...,8340.00,6152.17,2187.83,Credit Card,Delivered,"Moses, Ramirez and Morrow",emily42@houston-turner.org,13,No,0
996,ORD1996,2025-03-03,2025-03-08,CUST468,Abigail Patrick,Consumer,PROD7350,Cooking Oil,Grocery,East,...,3588.00,3180.70,407.30,UPI,Delivered,Brennan Group,oharris@combs-daniels.com,10,No,0
997,ORD1997,2024-11-09,2024-11-10,CUST126,David Gibson,Home Office,PROD1861,Pen,Office supplies,North,...,38632.50,28283.56,10348.94,Cash,Delivered,"Watson, Olsen and Young",millertroy@moss.org,10,No,0
998,ORD1998,2024-08-27,2024-08-28,CUST221,Kenneth James,Home Office,PROD8592,Dining Table,Furniture,West,...,10004.40,8177.27,1827.13,Credit Card,Pending,"Smith, Scott and Dillon",gburns@boyd-allen.org,39,No,0
999,ORD1999,2024-06-08,2024-06-13,CUST192,Benjamin Buchanan,Corporate,PROD1700,Notebook,Office supplies,East,...,1251.00,947.74,303.26,Cash,Cancelled,"Weber, Baker and Doyle",ericwilliams@johnson.info,0,Yes,29

# BASIC ANALYSIS

## 2. Finding Head

In [ ]:
df.head()

,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Customer Segment,Product ID,Product Name,Category,Region,...,Sales Amount,Cost Price,Profit,Payment Mode,Delivery Status,Supplier Name,Supplier Email,Stock Left,Auto Reorder,Reorder Quantity
0,ORD1000,2025-12-25,2025-12-27,CUST595,Sherry Thompson,Consumer,PROD6890,Dining Table,Furniture,North,...,4382.35,3653.39,728.96,UPI,Pending,Young Group,gford@peck-tucker.com,29,No,0
1,ORD1001,2024-04-08,2024-04-09,CUST183,Eric Olsen,Home Office,PROD3289,Snacks,Grocery,North,...,4858.30,4042.40,815.90,Cash,Cancelled,Fox-Williams,pattersonkimberly@clark.info,40,No,0
2,ORD1002,2025-01-29,2025-02-03,CUST590,John Armstrong,Consumer,PROD8638,Cooking Oil,Grocery,South,...,1579.20,959.15,620.05,Cash,Returned,Mann and Sons,brandonlutz@lopez.com,44,No,0
3,ORD1003,2025-05-29,2025-06-05,CUST582,Raymond Parker,Home Office,PROD5549,Mouse,Electronics,West,...,29421.00,19574.90,9846.10,Credit Card,Delivered,"Massey, Malone and Miller",norozco@miller.com,7,Yes,21
4,ORD1004,2025-03-02,2025-03-07,CUST530,Veronica Cole,Consumer,PROD4604,Cooking Oil,Grocery,South,...,32128.00,24292.49,7835.51,Cash,Delivered,Munoz-Robinson,dawn94@smith.com,27,No,0

## 3. Finding Tail

In [ ]:
df.tail()

,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Customer Segment,Product ID,Product Name,Category,Region,...,Sales Amount,Cost Price,Profit,Payment Mode,Delivery Status,Supplier Name,Supplier Email,Stock Left,Auto Reorder,Reorder Quantity
995,ORD1995,2024-09-10,2024-09-12,CUST985,Christopher Jordan,Corporate,PROD6665,Pen,Office supplies,North,...,8340.0,6152.17,2187.83,Credit Card,Delivered,"Moses, Ramirez and Morrow",emily42@houston-turner.org,13,No,0
996,ORD1996,2025-03-03,2025-03-08,CUST468,Abigail Patrick,Consumer,PROD7350,Cooking Oil,Grocery,East,...,3588.0,3180.70,407.30,UPI,Delivered,Brennan Group,oharris@combs-daniels.com,10,No,0
997,ORD1997,2024-11-09,2024-11-10,CUST126,David Gibson,Home Office,PROD1861,Pen,Office supplies,North,...,38632.5,28283.56,10348.94,Cash,Delivered,"Watson, Olsen and Young",millertroy@moss.org,10,No,0
998,ORD1998,2024-08-27,2024-08-28,CUST221,Kenneth James,Home Office,PROD8592,Dining Table,Furniture,West,...,10004.4,8177.27,1827.13,Credit Card,Pending,"Smith, Scott and Dillon",gburns@boyd-allen.org,39,No,0
999,ORD1999,2024-06-08,2024-06-13,CUST192,Benjamin Buchanan,Corporate,PROD1700,Notebook,Office supplies,East,...,1251.0,947.74,303.26,Cash,Cancelled,"Weber, Baker and Doyle",ericwilliams@johnson.info,0,Yes,29

## 4. Finding Type

In [ ]:
f'data type is : {type(df)}'

"data type is : <class 'pandas.core.frame.DataFrame'>"

## 5. Finding data type for each columns

In [ ]:
df.dtypes

Order ID             object
Order Date           object
Ship Date            object
Customer ID          object
Customer Name        object
Customer Segment     object
Product ID           object
Product Name         object
Category             object
Region               object
State                object
City                 object
Quantity              int64
Unit Price            int64
Discount              int64
Sales Amount        float64
Cost Price          float64
Profit              float64
Payment Mode         object
Delivery Status      object
Supplier Name        object
Supplier Email       object
Stock Left            int64
Auto Reorder         object
Reorder Quantity      int64
dtype: object

## 6.Finding random sample from dataset

In [ ]:
df.sample()

,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Customer Segment,Product ID,Product Name,Category,Region,...,Sales Amount,Cost Price,Profit,Payment Mode,Delivery Status,Supplier Name,Supplier Email,Stock Left,Auto Reorder,Reorder Quantity
843,ORD1843,2025-06-01,2025-06-02,CUST520,Lisa Tate,Corporate,PROD1837,Laptop,Electronics,South,...,10272.0,8622.08,1649.92,Cash,Pending,Patel-Riley,reginald56@hurley.biz,30,No,0

## 7. Finding summary of dataset

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          1000 non-null   object
 1   Order Date        1000 non-null   object
 2   Ship Date         1000 non-null   object
 3   Customer ID       1000 non-null   object
 4   Customer Name     1000 non-null   object
 5   Customer Segment  1000 non-null   object
 6   Product ID        1000 non-null   object
 7   Product Name      1000 non-null   object
 8   Category          1000 non-null   object
 9   Region            1000 non-null   object
 10  State             1000 non-null   object
 11  City              1000 non-null   object
 12  Quantity          1000 non-null   int64
 13  Unit Price        1000 non-null   int64
 14  Discount          1000 non-null   int64
 15  Sales Amount      1000 non-null   float64
 16  Cost Price        1000 non-null   float64
 17  Profit            1000 non-null   float64
 18  Payment Mode      1000 non-null   object
 19  Delivery Status   1000 non-null   object
 20  Supplier Name     1000 non-null   object
 21  Supplier Email    1000 non-null   object
 22  Stock Left        1000 non-null   int64
 23  Auto Reorder      1000 non-null   object
 24  Reorder Quantity  1000 non-null   int64
dtypes: float64(3), int64(5), object(17)
memory usage: 195.4+ KB

## 8. Finding all column name

In [ ]:
df.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Customer ID', 'Customer Name',
       'Customer Segment', 'Product ID', 'Product Name', 'Category', 'Region',
       'State', 'City', 'Quantity', 'Unit Price', 'Discount', 'Sales Amount',
       'Cost Price', 'Profit', 'Payment Mode', 'Delivery Status',
       'Supplier Name', 'Supplier Email', 'Stock Left', 'Auto Reorder',
       'Reorder Quantity'],
      dtype='object')

## 9.Find all data

In [ ]:
df

,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Customer Segment,Product ID,Product Name,Category,Region,...,Sales Amount,Cost Price,Profit,Payment Mode,Delivery Status,Supplier Name,Supplier Email,Stock Left,Auto Reorder,Reorder Quantity
0,ORD1000,2025-12-25,2025-12-27,CUST595,Sherry Thompson,Consumer,PROD6890,Dining Table,Furniture,North,...,4382.35,3653.39,728.96,UPI,Pending,Young Group,gford@peck-tucker.com,29,No,0
1,ORD1001,2024-04-08,2024-04-09,CUST183,Eric Olsen,Home Office,PROD3289,Snacks,Grocery,North,...,4858.30,4042.40,815.90,Cash,Cancelled,Fox-Williams,pattersonkimberly@clark.info,40,No,0
2,ORD1002,2025-01-29,2025-02-03,CUST590,John Armstrong,Consumer,PROD8638,Cooking Oil,Grocery,South,...,1579.20,959.15,620.05,Cash,Returned,Mann and Sons,brandonlutz@lopez.com,44,No,0
3,ORD1003,2025-05-29,2025-06-05,CUST582,Raymond Parker,Home Office,PROD5549,Mouse,Electronics,West,...,29421.00,19574.90,9846.10,Credit Card,Delivered,"Massey, Malone and Miller",norozco@miller.com,7,Yes,21
4,ORD1004,2025-03-02,2025-03-07,CUST530,Veronica Cole,Consumer,PROD4604,Cooking Oil,Grocery,South,...,32128.00,24292.49,7835.51,Cash,Delivered,Munoz-Robinson,dawn94@smith.com,27,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD1995,2024-09-10,2024-09-12,CUST985,Christopher Jordan,Corporate,PROD6665,Pen,Office supplies,North,...,8340.00,6152.17,2187.83,Credit Card,Delivered,"Moses, Ramirez and Morrow",emily42@houston-turner.org,13,No,0
996,ORD1996,2025-03-03,2025-03-08,CUST468,Abigail Patrick,Consumer,PROD7350,Cooking Oil,Grocery,East,...,3588.00,3180.70,407.30,UPI,Delivered,Brennan Group,oharris@combs-daniels.com,10,No,0
997,ORD1997,2024-11-09,2024-11-10,CUST126,David Gibson,Home Office,PROD1861,Pen,Office supplies,North,...,38632.50,28283.56,10348.94,Cash,Delivered,"Watson, Olsen and Young",millertroy@moss.org,10,No,0
998,ORD1998,2024-08-27,2024-08-28,CUST221,Kenneth James,Home Office,PROD8592,Dining Table,Furniture,West,...,10004.40,8177.27,1827.13,Credit Card,Pending,"Smith, Scott and Dillon",gburns@boyd-allen.org,39,No,0
999,ORD1999,2024-06-08,2024-06-13,CUST192,Benjamin Buchanan,Corporate,PROD1700,Notebook,Office supplies,East,...,1251.00,947.74,303.26,Cash,Cancelled,"Weber, Baker and Doyle",ericwilliams@johnson.info,0,Yes,29

In [ ]:
pd.set_option('display.max_rows',None)

## 10. Finding out the shape of dataset

In [ ]:
f'there are total rows and columns is : {df.shape}'

## 11. Finding out discription of dataset

In [ ]:
df.describe(include = 'object')

# Data Analysis

## data quality check

In [ ]:
print("\n== Data Quality Assesment==")
# Check for missing values
print ("\nmissing values:/n")
missing_data = df.isnull().sum()
print(missing_data[missing_data > 0])

# check for duplicates
print(f"\nDuplicate rows : {df.duplicated().sum()}")

## Data Type Conversion

In [ ]:
# convert date columns to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%Y-%m-%d')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%Y-%m-%d')

# check conversion
print("\nDate columns converted: \n")
print(f"Order Date: {df['Order Date'].dtype}")
print(f"Ship Date: {df['Ship Date'].dtype}")

## Univariate Analysis

In [ ]:
# Univariate Analysis is the simplest form of statistical analysis. As the name suggest- "uni"
# means "one" and "variate" means "variable"-it is the analysis of a single variable.

print("\n== Categorical variable ==\n")

categorical_cols = ['Customer Segment', 'Category', 'Region', 'Payment Mode', 'Delivery Status', 'Auto Reorder']

for col in categorical_cols:
    print(f"\n=={col}==")
    print(df[col].value_counts())

    #visualization
    plt.figure(figsize=(6, 6))
    df[col].value_counts().plot(kind='bar',color='skyblue')
    plt.title(f'Distriution of {col}')
    plt.xticks(rotation=30)
    plt.tight_layout()
    plt.show()

## Numerical Variabes Analysis

In [ ]:
print('\n== NUMERICAL VARIABLES ==\n')

numerical_cols = ['Quantity','Unit Price','Discount','Sales Amount','Cost Price','Profit','Stock Left','Reorder Quantity']

for col in numerical_cols:
    print(f"\n--{col}--\n")
    print(f"Mean: {df[col].mean():.2f}")
    print(f'Median: {df[col].median():.2f}')
    print(f'std dev: {df[col].std():.2f}')
    print(f'min: {df[col].min():.2f}')
    print(f'max: {df[col].max():.2f}')

    # Visualization
    plt.figure(figsize=(8,4))

    plt.subplot(1,2,1)
    df[col].hist(bins=30,color='lightgreen',alpha=0.7)
    plt.title(f'Distribution of {col}')

    plt.subplot(1,2,2)
    df.boxplot(column=col)
    plt.title(f'Boxplot of {col}')

    plt.tight_layout()
    plt.show()

## BIVARIATE ANALYSIS

In [ ]:
# Bivariate analysis is the statistical analysis of two variables the same time. The core purpose is to investigate the relationship between them.

print("\n==SALES & PROFIT BY CATEGORY ==\n")

category_performance = df.groupby("Category").agg({
    'Sales Amount': 'sum',
    'Profit': 'sum',
    'Order ID': 'count'
}).rename(columns={'Order ID': 'Order Count'})

category_performance['Profit Margin'] = (category_performance['Profit']/category_performance['Sales Amount'])*100
print(category_performance,'\n\n')

#Visualization
fig, axes = plt.subplots(2,2,figsize=(15,12))

# Sales By Category
category_performance['Sales Amount'].plot(kind='bar',ax=axes[0,0],color='blue',alpha=0.7)
axes[0,0].set_title('Total Sales By Category')
axes[0,0].tick_params(axis='x',rotation=30)

# Profit by Category
category_performance['Profit'].plot(kind='bar',ax=axes[0,1],color='green',alpha=0.7)
axes[0,1].set_title('Total Profit By Category')
axes[0,1].tick_params(axis='x',rotation=30)

# Profit Margin
category_performance['Profit Margin'].plot(kind='bar',ax=axes[1,0],color='orange',alpha=0.7)
axes[1,0].set_title('Total Profit Margin By Category')
axes[1,0].tick_params(axis='x',rotation=30)

# Order Count
category_performance['Order Count'].plot(kind='bar',ax=axes[1,1],color='blue',alpha=0.7)
axes[1,1].set_title('Total Order Count By Category')
axes[1,1].tick_params(axis='x',rotation=30)

plt.tight_layout()
plt.show()

## Regional Performance

In [ ]:
print('\n==REGIONAL PERFORMANCE==\n')

regional_performance = df.groupby("Region").agg({
    'Sales Amount': 'sum',
    'Profit': 'sum',
    'Order ID': 'count'
}).rename(columns={'Order ID': 'Order Count'})

regional_performance['Profit Margin'] = (regional_performance['Profit']/regional_performance['Sales Amount'])*100
print(regional_performance,'\n\n')

#Visualization
plt.figure(figsize=(12,8))

plt.subplot(2,2,1)
regional_performance['Sales Amount'].plot(kind='pie', autopct='%1.1f%%')
plt.title('Sales distribution by region')

plt.subplot(2,2,2)
regional_performance['Profit'].plot(kind='pie', autopct='%1.1f%%')
plt.title('Profit distribution by region')

plt.subplot(2,2,3)
sns.barplot(x=regional_performance.index, y='Order Count', data=regional_performance)
plt.title('Order Count by Region')
plt.xticks(rotation=30)

plt.subplot(2,2,4)
sns.barplot(x=regional_performance.index, y='Profit Margin', data=regional_performance)
plt.title('Profit Margin by Region(%)')
plt.xticks(rotation=30)

plt.tight_layout()
plt.show()

## TIME SRRIES ANALYSIS

In [ ]:
print('\n==TIME SERIES ANALYSIS==\n')

# Extract time component
df['Order Month'] = df['Order Date'].dt.to_period('M')
df['Order Year'] = df['Order Date'].dt.year

# Monthly trends
monthly_trends = df.groupby('Order Month').agg({
     'Sales Amount': 'sum',
    'Profit': 'sum',
    'Order ID': 'count'
}).rename(columns={'Order ID': 'Order Count'})

print('Monthly Trends:')
print(monthly_trends.tail(10),'n\n')

# visualization
plt.figure(figsize=(15,10))

plt.subplot(3,1,1)
monthly_trends['Sales Amount'].plot(kind='line',color='blue',marker='o')
plt.title('Monthly Sales Trend')
plt.ylabel('Sales Amount')
plt.grid(True)

plt.subplot(3,1,2)
monthly_trends['Profit'].plot(kind='line',color='green',marker='o')
plt.title('Monthly Profit Trend')
plt.ylabel('Profit')
plt.grid(True)

plt.subplot(3,1,3)
monthly_trends['Order Count'].plot(kind='line',color='red',marker='o')
plt.title('Monthly Order Count Trend')
plt.ylabel('Order Count')
plt.grid(True)

plt.tight_layout()
plt.show()

## ADVANCED ANALYSIS

In [ ]:
print('\n== CORRELATION ANALYSIS ==\n')

# select numerical column for correlation
numerical_df = df[['Quantity','Unit Price','Discount','Sales Amount','Cost Price','Profit']]

# correlation_matrix
correlation_matrix = numerical_df.corr()
print('correlation matrix : ')
print(correlation_matrix,'\n\n')

# HEATMAP
plt.figure(figsize=(10,8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm',center=0,
            square = True,linewidth=0.5)
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

## CUSTOMER SEGMENT ANALYSIS

In [ ]:
print('\n== CUSTOMER SEGMENT ANALYSIS ==\n')

segment_analysis = df.groupby('Customer Segment').agg({
    'Sales Amount' : ['sum','mean'],
    'Profit' : ['sum','mean'],
    'Order ID' : 'count',
    'Discount' : 'mean'
}).round(2)

segment_analysis.columns = ['Total Sales','Avg Sales','Total Profit','Avg Profit','Order Count','Avg Discount']
print(segment_analysis,'\n\n')

#visualization
fig, axes = plt.subplots(2,2,figsize=(15,10))

segment_analysis['Total Sales'].plot(kind='bar',ax=axes[0,0],color='lightblue')
axes[0,0].set_title('Total Sales By Customer Segment')
axes[0,0].tick_params(axis='x',rotation=30)

segment_analysis['Total Profit'].plot(kind='bar',ax=axes[0,1],color='orange')
axes[0,1].set_title('Total Profit By Customer Segment')
axes[0,1].tick_params(axis='x',rotation=30)

segment_analysis['Avg Sales'].plot(kind='bar',ax=axes[1,0],color='green')
axes[1,0].set_title('Average Profit By Customer Segment')
axes[1,0].tick_params(axis='x',rotation=30)

segment_analysis['Avg Discount'].plot(kind='bar',ax=axes[1,1],color='darkblue')
axes[1,1].set_title('Average Discount By Customer Segment')
axes[1,1].tick_params(axis='x',rotation=30)

plt.tight_layout()
plt.show()

# KEY INSIGHTS & SUMMARY

In [ ]:
print('\n== LEY INSIGHT SUMMARY ==\n')

# Overall Metrics
total_sales = df['Sales Amount'].sum()
total_profit = df['Profit'].sum()
total_orders = df['Order ID'].nunique()
avg_profit_margin = (total_profit/total_sales)*100

print(f'OVERALL PERFORMANCE:\n')
print(f'Total Sales: ${total_sales:,.2f}')
print(f'Total Profit: ${total_profit:,.2f}')
print(f'Total Orders: {total_orders}')
print(f'Average Profit Margin: {avg_profit_margin:.2f}%')

# Top Performing Categories
top_categories = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)
print(f'\nTOP PERFORMING CATEGORIES:\n')
for i, (category,profit) in enumerate(top_categories.items(),1):
    print(f"{i}.{category}:${profit:,.2f}")

# Regional Performing
best_region = df.groupby('Region')['Profit'].sum().idxmax()
print(f'nBEST PERFORMING REGION: {best_region}')

# DEelivery Performance
delivery_stats = df['Delivery Status'].value_counts(normalize=True)*100
print(f'\nDELIVERY STATUS:')
for status,percentage in delivery_stats.items():
    print(f'{status}: {percentage:.1f}%')

# Customer Segments
best_segment = df.groupby('Customer Segment')['Profit'].sum().index
print(f'\nMOST PROFITABLE CUSTOMER SEGMENT: {best_segment}')

# EXPORT RESULTS

In [ ]:
analysis_results = {
    'total_sales': total_sales,
    'total_profit': total_profit,
    'total_order': total_orders,
    'avg_profit_margin': avg_profit_margin,
    'top_category': top_categories.index[0],
    'best_region': best_region,
    'best_customer_segment': best_segment
}

# convert to dataframe and save
results_df = pd.DataFrame(analysis_results)
results_df.to_csv('eda_analysis_summary.csv', index= False)
print("\n Analysis summary saved to 'eda_analysis_summary.csv'")